import type { Session, SessionProvider } from '@agent-command/schema';
import * as db from '../db/index.js';
import * as automationDb from '../db/automationMemory.js';
import { sendInputToSession, waitForSessionReady } from './sessionSpawn.js';

type BootstrapSource = 'automatic' | 'automation';
type JsonObject = Record<string, unknown>;

export type MemoryFileExport = {
  base_dir: 'working_directory' | 'home';
  relative_path: string;
  content: string;
  scope: 'repo' | 'global' | 'local';
};

type MemoryPlan = {
  repoId: string | null;
  repoEntryIds: string[];
  globalEntryIds: string[];
  prompt: string | null;
  memoryFiles: MemoryFileExport[];
  fileExports: Array<{
    scope: 'repo' | 'global' | 'local';
    path: string;
    base_dir: 'working_directory' | 'home';
  }>;
};

function buildMemoryPrompt(input: {
  source: BootstrapSource;
  repoEntries: Array<{ summary: string; content: string }>;
  globalEntries: Array<{ summary: string; content: string }>;
  objective?: string | null;
  workItemText?: string | null;
  agentName?: string | null;
  fileExports?: MemoryPlan['fileExports'];
}): string | null {
  const fileExports = input.fileExports ?? [];
  const repoBlock = input.repoEntries.length > 0
    ? input.repoEntries.map((entry, index) => `${index + 1}. ${entry.summary}\n${entry.content}`).join('\n\n')
    : '';
  const globalBlock = input.globalEntries.length > 0
    ? input.globalEntries.map((entry, index) => `${index + 1}. ${entry.summary}\n${entry.content}`).join('\n\n')
    : '';
  const fileBlock = fileExports.length > 0
    ? fileExports.map((entry) => `- ${entry.scope}: ${entry.base_dir === 'home' ? '~/' : ''}${entry.path}`).join('\n')
    : '';

  if (
    !repoBlock
    && !globalBlock
    && !input.objective?.trim()
    && !input.workItemText?.trim()
    && !fileBlock
  ) {
    return null;
  }

  const parts = [
    input.source === 'automation'
      ? `Agent Commander automation context${input.agentName ? ` for ${input.agentName}` : ''}.`
      : 'Agent Commander memory context for this session.',
    input.objective ? `Objective:\n${input.objective}` : null,
    input.workItemText ? `Checked out work item:\n${input.workItemText}` : null,
    repoBlock ? `Repo memory:\n${repoBlock}` : null,
    globalBlock ? `Global memory:\n${globalBlock}` : null,
    fileBlock ? `Memory files exported for this session:\n${fileBlock}\nReview them directly if you need the durable version of this context.` : null,
  ].filter(Boolean);

  return parts.length > 0 ? parts.join('\n\n') : null;
}

function memorySections(entries: Array<{ tier: string; summary: string; content: string }>): string {
  if (entries.length === 0) {
    return 'No durable entries exported.';
  }

  return entries
    .map((entry, index) => [
      `## ${index + 1}. ${entry.summary}`,
      `Tier: ${entry.tier}`,
      '',
      entry.content,
    ].join('\n'))
    .join('\n\n');
}

function buildMemoryFiles(input: {
  provider: SessionProvider;
  repoEntries: Array<{ tier: string; summary: string; content: string }>;
  globalEntries: Array<{ tier: string; summary: string; content: string }>;
  workingDirectory?: string | null;
}): MemoryFileExport[] {
  if (input.provider !== 'claude_code' || !input.workingDirectory?.trim()) {
    return [];
  }

  const files: MemoryFileExport[] = [];
  if (input.repoEntries.length > 0) {
    files.push({
      base_dir: 'working_directory',
      relative_path: '.claude/agent-commander-memory.md',
      scope: 'repo',
      content: [
        '# Agent Commander Repo Memory',
        '',
        'This file is generated by Agent Commander before session startup.',
        'Treat it as durable repo-specific memory distilled from prior successful work.',
        '',
        memorySections(input.repoEntries),
      ].join('\n'),
    });
  }

  if (input.globalEntries.length > 0) {
    files.push({
      base_dir: 'home',
      relative_path: '.claude/agent-commander-global-memory.md',
      scope: 'global',
      content: [
        '# Agent Commander Global Memory',
        '',
        'This file is generated by Agent Commander before session startup.',
        'Treat it as durable cross-repo memory and operator preference context.',
        '',
        memorySections(input.globalEntries),
      ].join('\n'),
    });
  }

  return files;
}

async function resolveRepoId(input: {
  user_id: string;
  repo_id?: string | null;
  host_id?: string | null;
  working_directory?: string | null;
}): Promise<string | null> {
  if (input.repo_id) {
    return input.repo_id;
  }
  if (!input.host_id || !input.working_directory) {
    return null;
  }
  const repo = await db.findRepoByWorkingDirectory({
    user_id: input.user_id,
    host_id: input.host_id,
    working_directory: input.working_directory,
  });
  return repo?.id ?? null;
}

export async function prepareSessionMemoryForSpawn(input: {
  user_id: string;
  provider: SessionProvider;
  host_id?: string | null;
  working_directory?: string | null;
  repo_id?: string | null;
  source: BootstrapSource;
  objective?: string | null;
  workItemText?: string | null;
  agentName?: string | null;
}): Promise<MemoryPlan> {
  const repoId = await resolveRepoId({
    user_id: input.user_id,
    repo_id: input.repo_id || null,
    host_id: input.host_id || null,
    working_directory: input.working_directory || null,
  });
  const memory = await automationDb.getMemoryContextBrief(input.user_id, {
    repo_id: repoId,
    limitPerScope: 3,
  });
  const memoryFiles = buildMemoryFiles({
    provider: input.provider,
    repoEntries: memory.repo,
    globalEntries: memory.global,
    workingDirectory: input.working_directory || null,
  });
  const fileExports = memoryFiles.map((file) => ({
    scope: file.scope,
    path: file.relative_path,
    base_dir: file.base_dir,
  }));
  const prompt = buildMemoryPrompt({
    source: input.source,
    repoEntries: memory.repo,
    globalEntries: memory.global,
    objective: input.objective || null,
    workItemText: input.workItemText || null,
    agentName: input.agentName || null,
    fileExports,
  });

  return {
    repoId,
    repoEntryIds: memory.repo.map((entry) => entry.id),
    globalEntryIds: memory.global.map((entry) => entry.id),
    prompt,
    memoryFiles,
    fileExports,
  };
}

export async function bootstrapSessionMemory(input: {
  host_id: string;
  session_id: string;
  source: BootstrapSource;
  objective?: string | null;
  workItemText?: string | null;
  agentName?: string | null;
}): Promise<{
  session: Session | null;
  repoEntryIds: string[];
  globalEntryIds: string[];
  fileExports: MemoryPlan['fileExports'];
  skipped: boolean;
}> {
  const existing = await db.getSessionById(input.session_id);
  if (!existing?.user_id) {
    return { session: existing, repoEntryIds: [], globalEntryIds: [], fileExports: [], skipped: true };
  }

  const currentSession = existing.status === 'STARTING'
    ? await waitForSessionReady(existing.id, 30_000, 500)
    : existing;
  if (!currentSession?.user_id) {
    return { session: currentSession, repoEntryIds: [], globalEntryIds: [], fileExports: [], skipped: true };
  }

  const metadata = (currentSession.metadata ?? {}) as JsonObject;
  if (metadata.memory_bootstrap && input.source === 'automatic') {
    return { session: currentSession, repoEntryIds: [], globalEntryIds: [], fileExports: [], skipped: true };
  }

  const plan = await prepareSessionMemoryForSpawn({
    user_id: currentSession.user_id,
    provider: currentSession.provider,
    host_id: currentSession.host_id,
    working_directory: currentSession.cwd || currentSession.repo_root || null,
    repo_id: currentSession.repo_id || null,
    source: input.source,
    objective: input.objective || null,
    workItemText: input.workItemText || null,
    agentName: input.agentName || null,
  });

  if (!plan.prompt && plan.fileExports.length === 0) {
    return {
      session: currentSession,
      repoEntryIds: plan.repoEntryIds,
      globalEntryIds: plan.globalEntryIds,
      fileExports: plan.fileExports,
      skipped: true,
    };
  }

  if (plan.prompt) {
    await sendInputToSession({
      host_id: input.host_id,
      session_id: currentSession.id,
      text: plan.prompt,
      enter: true,
    });
  }
  await automationDb.recordMemoryAccess([
    ...plan.repoEntryIds,
    ...plan.globalEntryIds,
  ]);
  const updated = await db.patchSessionMetadata(currentSession.id, {
    memory_bootstrap: {
      sent_at: new Date().toISOString(),
      source: input.source,
      repo_entry_ids: plan.repoEntryIds,
      global_entry_ids: plan.globalEntryIds,
      total_entries: plan.repoEntryIds.length + plan.globalEntryIds.length,
      file_exports: plan.fileExports,
    },
  });

  return {
    session: updated ?? currentSession,
    repoEntryIds: plan.repoEntryIds,
    globalEntryIds: plan.globalEntryIds,
    fileExports: plan.fileExports,
    skipped: !plan.prompt,
  };
}
